/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: otpauth_migration.proto */

#ifndef PROTOBUF_C_otpauth_5fmigration_2eproto__INCLUDED
#define PROTOBUF_C_otpauth_5fmigration_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Payload Payload;
typedef struct _Payload__OtpParameters Payload__OtpParameters;


/* --- enums --- */


/* --- messages --- */

struct  _Payload__OtpParameters
{
  ProtobufCMessage base;
  ProtobufCBinaryData secret;
  char *name;
  char *issuer;
  int32_t algorithm;
  int32_t digits;
  int32_t type;
};
#define PAYLOAD__OTP_PARAMETERS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&payload__otp_parameters__descriptor) \
    , {0,NULL}, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0, 0 }


struct  _Payload
{
  ProtobufCMessage base;
  size_t n_otp_parameters;
  Payload__OtpParameters **otp_parameters;
  int32_t version;
  int32_t batch_size;
  int32_t batch_index;
  int32_t batch_id;
};
#define PAYLOAD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&payload__descriptor) \
    , 0,NULL, 0, 0, 0, 0 }


/* Payload__OtpParameters methods */
void   payload__otp_parameters__init
                     (Payload__OtpParameters         *message);
/* Payload methods */
void   payload__init
                     (Payload         *message);
size_t payload__get_packed_size
                     (const Payload   *message);
size_t payload__pack
                     (const Payload   *message,
                      uint8_t             *out);
size_t payload__pack_to_buffer
                     (const Payload   *message,
                      ProtobufCBuffer     *buffer);
Payload *
       payload__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   payload__free_unpacked
                     (Payload *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Payload__OtpParameters_Closure)
                 (const Payload__OtpParameters *message,
                  void *closure_data);
typedef void (*Payload_Closure)
                 (const Payload *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor payload__descriptor;
extern const ProtobufCMessageDescriptor payload__otp_parameters__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_otpauth_5fmigration_2eproto__INCLUDED */
