/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: otpauth_migration.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "otpauth_migration.pb-c.h"
void   payload__otp_parameters__init
                     (Payload__OtpParameters         *message)
{
  static const Payload__OtpParameters init_value = PAYLOAD__OTP_PARAMETERS__INIT;
  *message = init_value;
}
void   payload__init
                     (Payload         *message)
{
  static const Payload init_value = PAYLOAD__INIT;
  *message = init_value;
}
size_t payload__get_packed_size
                     (const Payload *message)
{
  assert(message->base.descriptor == &payload__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t payload__pack
                     (const Payload *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &payload__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t payload__pack_to_buffer
                     (const Payload *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &payload__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Payload *
       payload__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Payload *)
     protobuf_c_message_unpack (&payload__descriptor,
                                allocator, len, data);
}
void   payload__free_unpacked
                     (Payload *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &payload__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor payload__otp_parameters__field_descriptors[6] =
{
  {
    "secret",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Payload__OtpParameters, secret),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Payload__OtpParameters, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "issuer",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Payload__OtpParameters, issuer),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "algorithm",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Payload__OtpParameters, algorithm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "digits",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Payload__OtpParameters, digits),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Payload__OtpParameters, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned payload__otp_parameters__field_indices_by_name[] = {
  3,   /* field[3] = algorithm */
  4,   /* field[4] = digits */
  2,   /* field[2] = issuer */
  1,   /* field[1] = name */
  0,   /* field[0] = secret */
  5,   /* field[5] = type */
};
static const ProtobufCIntRange payload__otp_parameters__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor payload__otp_parameters__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Payload.OtpParameters",
  "OtpParameters",
  "Payload__OtpParameters",
  "",
  sizeof(Payload__OtpParameters),
  6,
  payload__otp_parameters__field_descriptors,
  payload__otp_parameters__field_indices_by_name,
  1,  payload__otp_parameters__number_ranges,
  (ProtobufCMessageInit) payload__otp_parameters__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor payload__field_descriptors[5] =
{
  {
    "otp_parameters",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Payload, n_otp_parameters),
    offsetof(Payload, otp_parameters),
    &payload__otp_parameters__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Payload, version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "batch_size",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Payload, batch_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "batch_index",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Payload, batch_index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "batch_id",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Payload, batch_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned payload__field_indices_by_name[] = {
  4,   /* field[4] = batch_id */
  3,   /* field[3] = batch_index */
  2,   /* field[2] = batch_size */
  0,   /* field[0] = otp_parameters */
  1,   /* field[1] = version */
};
static const ProtobufCIntRange payload__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor payload__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Payload",
  "Payload",
  "Payload",
  "",
  sizeof(Payload),
  5,
  payload__field_descriptors,
  payload__field_indices_by_name,
  1,  payload__number_ranges,
  (ProtobufCMessageInit) payload__init,
  NULL,NULL,NULL    /* reserved[123] */
};
