name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y protobuf-c-compiler libprotobuf-c-dev gcc make dpkg-dev

      - name: Build project
        run: make

      - name: Package as .deb
        run: |
          mkdir -p dist/linux
          cp bin/g2fa-extractor dist/linux/
          cd dist/linux
          fpm -s dir -t deb -n g2fa-secret-extractor -v ${GITHUB_REF##*/v} g2fa-extractor=/usr/local/bin/g2fa-extractor

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: g2fa-secret-extractor-linux
          path: dist/linux/*.deb

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: choco install make mingw -y

      - name: Build project
        run: make CC=x86_64-w64-mingw32-gcc

      - name: Package as .exe
        run: |
          mkdir -p dist/windows
          cp bin/g2fa-extractor.exe dist/windows/

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: g2fa-secret-extractor-windows
          path: dist/windows/*.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: brew install protobuf-c

      - name: Build project
        run: make

      - name: Package as .dmg
        run: |
          mkdir -p dist/macos
          hdiutil create dist/macos/g2fa-secret-extractor.dmg -volname g2fa-secret-extractor -srcfolder bin/

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: g2fa-secret-extractor-macos
          path: dist/macos/*.dmg

  release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows, build-macos]
    steps:
      - name: Download Linux artifact
        uses: actions/download-artifact@v3
        with:
          name: g2fa-secret-extractor-linux

      - name: Download Windows artifact
        uses: actions/download-artifact@v3
        with:
          name: g2fa-secret-extractor-windows

      - name: Download macOS artifact
        uses: actions/download-artifact@v3
        with:
          name: g2fa-secret-extractor-macos

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          artifacts: |
            dist/linux/*.deb
            dist/windows/*.exe
            dist/macos/*.dmg
