name: Build and Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y protobuf-c-compiler libprotobuf-c-dev gcc make dpkg-dev ruby ruby-dev
          sudo gem install fpm

      - name: Build project
        run: make

      - name: Package as .deb
        run: |
          mkdir -p dist/linux
          cp bin/g2fa-extractor dist/linux/
          cd dist/linux
          fpm -s dir -t deb -n g2fa-secret-extractor -v ${GITHUB_REF##*/v} g2fa-extractor=/usr/local/bin/g2fa-extractor

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: g2fa-secret-extractor-linux
          path: dist/linux/*.deb

  release:
    runs-on: ubuntu-latest
    needs: [build-linux]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Linux artifact
        uses: actions/download-artifact@v3
        with:
          name: g2fa-secret-extractor-linux
          path: dist/linux/

      - name: List downloaded files
        run: ls -lh dist/linux/

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
          artifacts: dist/linux/*.deb
