name: Build and Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-ubuntu-20_04:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y protobuf-c-compiler libprotobuf-c-dev gcc make dpkg-dev

      - name: Build project
        run: make

      - name: Package as .deb using dpkg-deb
        run: |
          mkdir -p dist/ubuntu-20.04/g2fa-secret-extractor/usr/local/bin
          cp bin/g2fa-extractor dist/ubuntu-20.04/g2fa-secret-extractor/usr/local/bin/
          mkdir -p dist/ubuntu-20.04/g2fa-secret-extractor/DEBIAN
          echo "Package: g2fa-secret-extractor" > dist/ubuntu-20.04/g2fa-secret-extractor/DEBIAN/control
          echo "Version: ${GITHUB_REF##*/v}" >> dist/ubuntu-20.04/g2fa-secret-extractor/DEBIAN/control
          echo "Architecture: amd64" >> dist/ubuntu-20.04/g2fa-secret-extractor/DEBIAN/control
          echo "Maintainer: Hai Pham Ngoc <ngochai285nd@gmail.com>" >> dist/ubuntu-20.04/g2fa-secret-extractor/DEBIAN/control
          echo "Description: G2FA Secret Extractor" >> dist/ubuntu-20.04/g2fa-secret-extractor/DEBIAN/control
          dpkg-deb --build dist/ubuntu-20.04/g2fa-secret-extractor

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: g2fa-secret-extractor-ubuntu-20.04
          path: dist/ubuntu-20.04/*.deb

  release:
    runs-on: ubuntu-latest
    needs: [build-ubuntu-20_04]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifact (Ubuntu 20.04)
        uses: actions/download-artifact@v3
        with:
          name: g2fa-secret-extractor-ubuntu-20.04

      - name: List downloaded files
        run: ls -lh dist/

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
          artifacts: |
            dist/ubuntu-20.04/*.deb
